# Generated by CMake, DO NOT EDIT

empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mac/Documents/GITRepositories/libigl/external/glad/CMakeLists.txt))

/Users/mac/Documents/GITRepositories/Dev-2-libigl/XcodeProject/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Applications/CMake.app/Contents/bin/cmake -H/Users/mac/Documents/GITRepositories/Dev-2-libigl -B/Users/mac/Documents/GITRepositories/Dev-2-libigl/XcodeProject
